# Default values
highlight_color = "LightBlue"
cursor = "█"
terminal_launcher = "alacritty -e"
hard_stop = false

# UI Customization
rounded_borders = true

# Border Colors (individual colors for each panel)
# Color formats supported:
#   - Named colors: "Red", "Blue", "Green", "Yellow", "Cyan", "Magenta", "White", "Black"
#                   "LightRed", "LightBlue", "LightGreen", "LightYellow", "LightCyan", "LightMagenta"
#                   "Gray"/"Grey", "DarkGray"/"DarkGrey", "Reset"
#   - Hex colors: "#ff0000" (red), "#00ff00" (green), "#0000ff" (blue)
#   - Short hex: "#f00" (red), "#0f0" (green), "#00f" (blue)
#   - RGB colors: "rgb(255,0,0)" or "(255,0,0)"
#   - 8-bit colors: "196" (bright red), "21" (bright blue), "46" (bright green)
main_border_color = "White"      # Border color for the main info panel (top)
apps_border_color = "White"      # Border color for the apps list panel (middle)
input_border_color = "White"     # Border color for the input panel (bottom)

# Text Colors (non-highlighted text in each panel)
main_text_color = "White"        # Text color for the main info panel
apps_text_color = "White"        # Text color for the apps list
input_text_color = "White"       # Text color for the input field

# Fancy Mode - Show selected app info in panel titles
fancy_mode = false               # When true: "Apps" becomes selected app name, "Gyr" becomes app description

# Header title color (for panel border titles)
header_title_color = "LightBlue" # Color for all panel header titles

# Layout Configuration (percentages and sizes)
title_panel_height_percent = 30  # Height of top panel as percentage (10-70%)
input_panel_height = 3           # Height of input panel in lines (1-10)
# Note: Apps panel gets the remaining space automatically

# ===== DMENU MODE CONFIGURATION =====
# Settings specific to dmenu mode (--dmenu flag)
# If not specified, regular mode settings are used as fallback
[dmenu]

# Dmenu-specific colors (override regular mode when in dmenu)
highlight_color = "LightBlue"     # Highlighted text and cursor color
cursor = "█"                     # Cursor character in filter input

# Dmenu border colors (separate from regular mode)
main_border_color = "White"      # Border color for content panel (top)
items_border_color = "White"     # Border color for items list panel (middle)
input_border_color = "White"     # Border color for filter panel (bottom)

# Dmenu text colors
main_text_color = "White"        # Text color in content panel
items_text_color = "White"       # Text color in items list
input_text_color = "White"       # Text color in filter field

# Dmenu UI settings
rounded_borders = true           # Use rounded borders in dmenu mode
hard_stop = false                # Don't wrap around at list ends
header_title_color = "LightBlue" # Color for panel titles

# Dmenu layout (different from regular mode)
content_panel_height_percent = 40  # Height of content panel as percentage (10-70%)
input_panel_height = 3             # Height of filter panel in lines (1-10)
# Note: Items panel gets the remaining space

# Dmenu parsing options
delimiter = " "                  # Default column delimiter (can be overridden by --delimiter)
show_line_numbers = true        # Show line numbers in content display
wrap_long_lines = true           # Wrap long lines in content panel

